<?php

declare(strict_types=1);

namespace Utils\Rector\NamespaceMap;

use Composer\Autoload\ClassLoader;
use PhpParser\Node;
use PhpParser\Node\Stmt\ClassLike;
use PhpParser\Node\Stmt\Namespace_;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitorAbstract;
use PhpParser\Parser;
use PhpParser\ParserFactory;
use Utils\Rector\Namespace\RootNamespace;

/**
 * Generates the Piwik\* -> Matomo\* class map that feeds RenameClassRector and
 * RenameStringRector. Every Piwik\-namespaced class is mapped by a root-prefix
 * swap; the facade Piwik\Piwik (whose short name changes) is overridden to
 * Matomo\Matomo. Reused as-is by every submodule repo, which builds the map
 * from its own Composer PSR-4 roots.
 *
 * The map is generated by parsing each file under a Piwik\ PSR-4 root and
 * reading the declared namespace + class/interface/trait/enum name, so it is
 * correct for non-PSR-4-conforming files too (multiple classes per file,
 * class name not matching the file name). The map is exhaustive over declared
 * classes; any class missed here is caught by the migrated-source "no Piwik\
 * namespace refs" guard.
 */
final class NamespaceMap
{
    /** @var array<string, string> */
    private array $map;

    /**
     * @param array<string, string> $map
     */
    public function __construct(array $map)
    {
        $this->map = $map;
    }

    /**
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return $this->map;
    }

    /**
     * Build the map from a Composer ClassLoader by scanning every Piwik\ PSR-4
     * root for declared class-likes.
     */
    public static function fromClassLoader(ClassLoader $loader): self
    {
        $prefixToDirs = [];
        foreach ($loader->getPrefixesPsr4() as $prefix => $dirs) {
            if (strpos($prefix, RootNamespace::OLD_PREFIX) === 0) {
                $prefixToDirs[$prefix] = $dirs;
            }
        }

        return self::fromPrefixPaths($prefixToDirs);
    }

    /**
     * Build the map from an explicit PSR-4 prefix=>dirs mapping by scanning the
     * directories for declared class-likes. Exposed for testing.
     *
     * @param array<string, string[]> $prefixToDirs
     */
    public static function fromPrefixPaths(array $prefixToDirs): self
    {
        $map = [];
        $parser = (new ParserFactory())->createForHostVersion();

        foreach ($prefixToDirs as $dirs) {
            foreach ($dirs as $dir) {
                foreach (self::phpFiles($dir) as $file) {
                    foreach (self::declaredFqca($parser, $file) as $fqcn) {
                        if (strpos($fqcn, RootNamespace::OLD_PREFIX) !== 0) {
                            continue;
                        }

                        if ($fqcn === RootNamespace::FACADE_OLD) {
                            $map[$fqcn] = RootNamespace::FACADE_NEW;
                        } else {
                            $map[$fqcn] = RootNamespace::NEW_PREFIX . substr($fqcn, strlen(RootNamespace::OLD_PREFIX));
                        }
                    }
                }
            }
        }

        ksort($map);

        return new self($map);
    }

    /**
     * @return iterable<string>
     */
    private static function phpFiles(string $dir): iterable
    {
        if (!is_dir($dir)) {
            return;
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if ($file->getExtension() === 'php') {
                yield $file->getPathname();
            }
        }
    }

    /**
     * @return string[]
     */
    private static function declaredFqca(Parser $parser, string $file): array
    {
        $code = @file_get_contents($file);

        if ($code === false) {
            return [];
        }

        try {
            $statements = $parser->parse($code);
        } catch (\Throwable $e) {
            return [];
        }

        if ($statements === null) {
            return [];
        }

        $collector = new class extends NodeVisitorAbstract {
            /** @var string|null */
            public $namespace;

            /** @var string[] */
            public $fqca = [];

            public function enterNode(Node $node)
            {
                if ($node instanceof Namespace_) {
                    $this->namespace = $node->name !== null ? $node->name->toString() : null;

                    return null;
                }

                if ($node instanceof ClassLike && $node->name !== null) {
                    $this->fqca[] = ($this->namespace !== null ? $this->namespace . '\\' : '') . $node->name->toString();
                }

                return null;
            }

            public function leaveNode(Node $node)
            {
                if ($node instanceof Namespace_) {
                    $this->namespace = null;
                }

                return null;
            }
        };

        $traverser = new NodeTraverser();
        $traverser->addVisitor($collector);
        $traverser->traverse($statements);

        return $collector->fqca;
    }
}
